# Generated by Django 2.0.3 on 2018-03-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0002_auto_20180323_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='time_visited',
            field=models.DateTimeField(null=True),
        ),
    ]
