# Generated by Django 2.0.3 on 2018-03-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0003_auto_20180323_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='time_visited',
            field=models.DateField(null=True),
        ),
    ]
