# Generated by Django 2.0.3 on 2018-03-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0004_auto_20180323_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='time_visited',
            new_name='date_visited',
        ),
    ]
